services:
    brave:
    image: lscr.io/linuxserver/brave:latest
    container_name: brave
    network_mode: service:gluetun
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./brave-vpn/config:/config
    depends_on:
      - gluetun
    #ports:
     # - 3000:3000 # brave
      #- 3001:3001 # braveHTTPS
    shm_size: 1gb
    restart: unless-stopped

  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
      - SYS_RESOURCE
    volumes:
      - ./tailscale/var/lib:/var/lib
      - ./tailscale/state:/state
      - /dev/net/tun:/dev/net/tun
    # network_mode: "service:gluetun" <-- THIS BREAKS DIRECT CONNECTION
    # network_mode: "host" # direct connection works, but can't use gluetun
    # network_mode: "bridge" # direct connection works most of the times (as double NAT), but can't use gluetun
    restart: unless-stopped
    environment:
      - PORT=${PORT}
      - TS_HOSTNAME=${TS_HOSTNAME}
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_EXTRA_ARGS=${TS_EXTRA_ARGS}
      - TS_ACCEPT_ROUTES=${TS_ACCEPT_ROUTES}
      - TS_ROUTES=${TS_ROUTES}
      - TS_NO_LOGS_NO_SUPPORT=${TS_NO_LOGS_NO_SUPPORT}
      - TS_STATE_DIR=${TS_STATE_DIR}
      - TS_USERSPACE=${TS_USERSPACE}
    depends_on:
      gluetun:
        condition: service_healthy

  # gluetun:
  #   image: qmcgaw/gluetun:v3.40.0
  #   container_name: tsgluetun
  #   # line above must be uncommented to allow external containers to connect.
  #   # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
  #   cap_add:
  #     - NET_ADMIN
  #   devices:
  #     - /dev/net/tun:/dev/net/tun
  #   ports:
  #     - 6881:6881
  #     - 6881:6881/udp
  #     - 51413:51413
  #     - 51413:51413/udp
  #     - 51820:51820 # wireguard port
  #     - 58846:58846 #optional
  #     - 3000:3000 # brave
  #     - 3001:3001 # brave2
  #     - 8001:8000 #http-port
  #   volumes:
  #     - ./glutun:/gluetun
  #   environment:
  #     # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
  #     # OpenVPN:
  #     #- VPN_SERVICE_PROVIDER=Surfshark
  #     #- VPN_TYPE=openvpn
  #     #- OPENVPN_USER=BBf2XVP9UjAVSPV5uxS84cww
  #     #- OPENVPN_PASSWORD=tj5kLLzJPv8W5cT3EMeN7Ej5
  #     # Wireguard:
  #     - VPN_SERVICE_PROVIDER=Surfshark
  #     - VPN_TYPE=wireguard
  #     - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY} # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/nordvpn.md#obtain-your-wireguard-private-key
  #     - WIREGUARD_PUBLIC_KEY=${WIREGUARD_PUBLIC_KEY}
  #     - WIREGUARD_ADDRESSES=10.14.0.2/16
  #     - WIREGUARD_ENDPOINT=uk-man.prod.surfshark.com:51820
  #     - WIREGUARD_DNS=162.252.172.57,149.154.159.92
  #     - VPN_CITIES=London,Manchester,Glasgow,Edinburgh
  #     - SERVER_COUNTRIES=UNITED KINGDOM
  #     # Timezone for accurate log times
  #     - TZ=Europe/London
  #     # Server list updater
  #     # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
  #     - UPDATER_PERIOD=6h
  #     - FIREWALL_OUTBOUND_SUBNETS=172.18.0.0/24,192.168.68.0/24,192.168.69.0/24 # exposing subnets to glutun
  #     - HTTP_CONTROL_SERVER_ADDRESS=:8000 # homepage_widget
  #     - HTTP_CONTROL_SERVER_LOG=ON # homepage_widget
  #     #- HTTP_CONTROL_SERVER_AUTH_CONFIG_FILEPATH=/home/linuxadmin/appdata/glutun
  #   restart: always
