services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: always
    extra_hosts:
      - "grafana-monitoring:host-gateway"
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
      - grafana_data:/var/lib/grafana
  influxdb:
    image: influxdb:2.7.6-alpine
    container_name: influxdb2
    ports:
      - 8086:8086
    extra_hosts:
      - "grafana-monitoring:host-gateway"
    volumes:
      - influxdb2_data:/var/lib/influxdb2
      - ./influxdb2/config:/etc/influxdb2
      - ./influxdb2/scripts:/docker-entrypoint-initdb.d
    restart: always
  telegraf:
    image: telegraf:latest
    pid: "host"
    container_name: telegraf
    user: telegraf:990 # make sure to run 'getent group docker' on the host for appropriate group number for docker.
    restart: always
    entrypoint: /bin/bash -c "/entrypoint.sh telegraf"
    extra_hosts:
      - "grafana-monitoring:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /:/hostfs:ro
    environment:
      - HOST_ETC=${HOST_ETC}
      - HOST_PROC=${HOST_PROC}
      - HOST_SYS=${HOST_SYS}
      - HOST_VAR=${HOST_VAR}
      - HOST_RUN=${HOST_RUN}
      - HOST_MOUNT_PREFIX=${HOST_MOUNT_PREFIX}
#  pihole-exporter:
#    image: 'ekofr/pihole-exporter:latest'
#    ports:
#      - '9617:9617'
#    environment:
#      - 'PORT=9617'
#      - 'PIHOLE_PORT=80,80,80'
#      - 'PIHOLE_API_TOKEN=P1holeunbound4b,P1holeunbound3b,P1holeunboundlxc'
#      - 'PIHOLE_HOSTNAME=192.168.68.151,192.168.68.152,192.168.68.153'
#      - 'PIHOLE_PROTOCOL=http,http,http'
volumes:
  prom_data:
  grafana_data:
  influxdb2_data:
