---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks

- Repositories:
    - Stumpy's Github:
        - abbr: S
          href: https://github.com/Stum9y

    - DB-Tech Github:
        - abbr: Db
          href: https://github.com/dnburgess

    - Christan Lempa Github:
        - abbr: C
          href: https://github.com/ChristianLempa

    - Jims Garage Github:
        - abbr: J
          href: https://github.com/JamesTurland/JimsGarage

    - TECH HUT TV Github:
        - abbr: THTV
          href: https://github.com/TechHutTV

    - VirttuliseHow2 Github:
        - abbr: Vh2
          href: https://github.com/brandonleegit

    - Docker-Github:
        - abbr: T
          href: https://github.com/docker

    - Portainer-Docs:
        - abbr: Pd
          href: https://docs.portainer.io/start/install-ce/server/docker/linux

    - TTECK's Proxmox Scripts:
        - abbr: T
          href: https://tteck.github.io/Proxmox

- Entertainment:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/

    - Twitch:
        - abbr: TTv
          href: https://www.twitch.tv/

- Social:
    - Reddit:
        - abbr: R
          href: https://reddit.com/

    - Facebook:
        - abbr: FB
          href: https://www.facebook.com/

    - Instagram:
        - abbr: I
          href: https://www.instagram.com/

    - Twitter:
        - abbr: T
          href: https://x.com/home

- Cloud Services:

    - Cloudflare Dashboard:
        - abbr: C
          href: https://dash.cloudflare.com/login

#    - Proxmin-Dashboard-Dell:
#        - abbr: C
#          href: https://dash.cloudflare.com/login

- Web-Links:

    - SelfHosted-News:
        - abbr: S
          href: https://selfh.st

    - Homepage Dev:
        - abbr: H
          href: https://gethomepage.dev

    - Tech-Hut:
        - abbr: Th
          href: https://techhut.tv/

    - Simple-Icons:
        - abbr: Si
          href: https://simpleicons.org/

    - Samknows-Speedtest:
        - abbr: Sk
          href: https://samknows.com/realspeed/

    - Nvidia Driver Download:
        - abbr: N
          href: https://www.nvidia.com/en-gb/drivers/

    - IT-Tools:
        - abbr: It
          href: http://192.168.68.106:8081
