---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings
title: Stumpy-Tech Homepage

Theme:
background:
    image: https://s3.amazonaws.com/speedhunters-wp-production/wp-content/uploads/2022/11/09205643/CSFRS6-V2-30-1200x800.jpg
    blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
    saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
    brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
    opacity: 50 # 0-100

theme: dark
color: sky

layout:
  Dashboards:
    style: column
#    columns: 5
  Networking:
    style: column
#    columns: 5
  Virtulisation & Storage:
    style: column
#    columns: 5
  Media-Libary:
    style: column
#    column: 4
  Docker:
    style: column
  Media-Sharing-Apps:
    style: column
#    columns: 4
  Calendar:
#    column: 4

headerStyle: boxedWidgets
fiveColumns: true
useEqualHeights: true

# providers:
#   openweathermap: openweathermapapikey
#   weatherapi: weatherapiapikey
