services:
    portainer-ce:
        ports:
            - 8000:8000
            - 9000:9000
            - 9443:9443
        container_name: portainer-ce
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /home/linuxadmin/docker/portainer/data:/data
        image: portainer/portainer-ce:latest

