---
version: "2.1"
services:
  adguardhome-sync:
    image: ghcr.io/bakito/adguardhome-sync
    container_name: adguardhome-sync
    command: run
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      ORIGIN_URL: ${ORIGIN_URL}
      # ORIGIN_WEB_URL: "https://some-other.url" # used in the web interface (default: <origin-url>
      ORIGIN_USERNAME: ${ORIGIN_USERNAME}
      ORIGIN_PASSWORD: ${ORIGIN_PASSWORD}
      
      REPLICA_URL: ${REPLICA_URL}
      REPLICA_USERNAME: ${REPLICA_USERNAME}
      REPLICA_PASSWORD: ${REPLICA_PASSWORD}
      
      # REPLICA1_URL: "http://192.168.68.66:88"
      # REPLICA1_USERNAME: "SynologyGuard"
      # REPLICA1_PASSWORD: "SynologyGuard"
      # REPLICA1_API_PATH: "/some/path/control"
      # REPLICA1_WEB_URL: "https://some-other.url" # used in the web interface (default: <replica-url>
      # REPLICA1_AUTO_SETUP: true # if true, AdGuardHome is automatically initialized.
      # REPLICA1_INTERFACE_NAME: 'ens18' # use custom dhcp interface name
      # REPLICA1_DHCP_SERVER_ENABLED: true/false (optional) enables/disables the dhcp server on the replica
      CRON: ${CRON}
      RUNONSTART: ${RUNONSTART}
      # CONTINUE_ON_ERROR: false # If enabled, the synchronisation task will not fail on single errors, but will log the errors and continue

      # Configure the sync API server, disabled if api port is 0
      API_PORT: 8080

      # Configure sync features; by default all features are enabled.
      # FEATURES_GENERAL_SETTINGS: true
      # FEATURES_QUERY_LOG_CONFIG: true
      # FEATURES_STATS_CONFIG: true
      # FEATURES_CLIENT_SETTINGS: true
      # FEATURES_SERVICES: true
      # FEATURES_FILTERS: true
      # FEATURES_DHCP_SERVER_CONFIG: true
      # FEATURES_DHCP_STATIC_LEASES: true
      # FEATURES_DNS_SERVER_CONFIG: true
      # FEATURES_DNS_ACCESS_LISTS: true
      # FEATURES_DNS_REWRITES: true
    ports:
      - 9876:8080
    restart: unless-stopped