--- 
version: "2"
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /srv/dev-disk-by-uuid-ee7d277c-c717-41ca-a756-6b4f31febde6/Docker-Data/nextcloud:/var/www/html
      - /srv/dev-disk-by-uuid-ee7d277c-c717-41ca-a756-6b4f31febde6/Docker-Data/nextcloud/apps:/var/www/html/custom_apps
      - /srv/dev-disk-by-uuid-ee7d277c-c717-41ca-a756-6b4f31febde6/Docker-Config/nextcloud/config:/var/www/html/config
      - /srv/dev-disk-by-uuid-ee7d277c-c717-41ca-a756-6b4f31febde6/Docker-Data/nextcloud/data:/var/www/html/data
      - /srv/dev-disk-by-uuid-ee7d277c-c717-41ca-a756-6b4f31febde6/Docker-Data/nextcloud/theme:/var/www/html/themes
    ports:
      - 86:80
      - 443:443
    restart: always

  db:
    image: mariadb:10.11
    volumes: 
      - /srv/dev-disk-by-uuid-ee7d277c-c717-41ca-a756-6b4f31febde6/Docker-Data/mariadb/db:/var/lib/mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    restart: always